package com.spring.boot.JspProject.model;
// Generated Jul 11, 2017 6:03:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataMenu generated by hbm2java
 */
@Entity
@Table(name="data_menu"
    ,catalog="db_menu_permissions"
)
public class DataMenu  implements java.io.Serializable {


     private String dataIdMenu;
     private String namaMenu;
     private String levelMenu;
     private String idMenu;
     private String className;
     private String linkMenu;
     private Set<RolesMenu> rolesMenus = new HashSet<RolesMenu>(0);

    public DataMenu() {
    }

	
    public DataMenu(String dataIdMenu, String namaMenu, String levelMenu, String className, String linkMenu) {
        this.dataIdMenu = dataIdMenu;
        this.namaMenu = namaMenu;
        this.levelMenu = levelMenu;
        this.className = className;
        this.linkMenu = linkMenu;
    }
    public DataMenu(String dataIdMenu, String namaMenu, String levelMenu, String idMenu, String className, String linkMenu, Set<RolesMenu> rolesMenus) {
       this.dataIdMenu = dataIdMenu;
       this.namaMenu = namaMenu;
       this.levelMenu = levelMenu;
       this.idMenu = idMenu;
       this.className = className;
       this.linkMenu = linkMenu;
       this.rolesMenus = rolesMenus;
    }
   
     @Id 

    
    @Column(name="data_id_menu", unique=true, nullable=false, length=36)
    public String getDataIdMenu() {
        return this.dataIdMenu;
    }
    
    public void setDataIdMenu(String dataIdMenu) {
        this.dataIdMenu = dataIdMenu;
    }

    
    @Column(name="nama_menu", nullable=false, length=100)
    public String getNamaMenu() {
        return this.namaMenu;
    }
    
    public void setNamaMenu(String namaMenu) {
        this.namaMenu = namaMenu;
    }

    
    @Column(name="level_menu", nullable=false, length=5)
    public String getLevelMenu() {
        return this.levelMenu;
    }
    
    public void setLevelMenu(String levelMenu) {
        this.levelMenu = levelMenu;
    }

    
    @Column(name="id_menu", length=36)
    public String getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(String idMenu) {
        this.idMenu = idMenu;
    }

    
    @Column(name="class_name", nullable=false, length=100)
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

    
    @Column(name="link_menu", nullable=false, length=50)
    public String getLinkMenu() {
        return this.linkMenu;
    }
    
    public void setLinkMenu(String linkMenu) {
        this.linkMenu = linkMenu;
    }

@OneToMany(mappedBy="dataMenu")
    public Set<RolesMenu> getRolesMenus() {
        return this.rolesMenus;
    }
    
    public void setRolesMenus(Set<RolesMenu> rolesMenus) {
        this.rolesMenus = rolesMenus;
    }




}


