package com.spring.boot.JspProject.model;
// Generated Jul 11, 2017 6:03:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,catalog="db_menu_permissions"
)
public class Roles  implements java.io.Serializable {


     private String roleId;
     private String nama;
     private Set<UserRole> userRoles = new HashSet<UserRole>(0);
     private Set<RolesMenu> rolesMenus = new HashSet<RolesMenu>(0);

    public Roles() {
    }

	
    public Roles(String roleId, String nama) {
        this.roleId = roleId;
        this.nama = nama;
    }
    public Roles(String roleId, String nama, Set<UserRole> userRoles, Set<RolesMenu> rolesMenus) {
       this.roleId = roleId;
       this.nama = nama;
       this.userRoles = userRoles;
       this.rolesMenus = rolesMenus;
    }
   
     @Id 

    
    @Column(name="role_id", unique=true, nullable=false, length=36)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="nama", nullable=false, length=45)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

@OneToMany(mappedBy="roles")
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }

@OneToMany(mappedBy="roles")
    public Set<RolesMenu> getRolesMenus() {
        return this.rolesMenus;
    }
    
    public void setRolesMenus(Set<RolesMenu> rolesMenus) {
        this.rolesMenus = rolesMenus;
    }




}


