package com.spring.boot.JspProject.model;
// Generated Jul 11, 2017 6:03:19 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolesMenuId generated by hbm2java
 */
@Embeddable
public class RolesMenuId  implements java.io.Serializable {


     private String dataIdMenu;
     private String roleId;

    public RolesMenuId() {
    }

    public RolesMenuId(String dataIdMenu, String roleId) {
       this.dataIdMenu = dataIdMenu;
       this.roleId = roleId;
    }
   


    @Column(name="data_id_menu", nullable=false, length=36)
    public String getDataIdMenu() {
        return this.dataIdMenu;
    }
    
    public void setDataIdMenu(String dataIdMenu) {
        this.dataIdMenu = dataIdMenu;
    }


    @Column(name="role_id", nullable=false, length=36)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolesMenuId) ) return false;
		 RolesMenuId castOther = ( RolesMenuId ) other; 
         
		 return ( (this.getDataIdMenu()==castOther.getDataIdMenu()) || ( this.getDataIdMenu()!=null && castOther.getDataIdMenu()!=null && this.getDataIdMenu().equals(castOther.getDataIdMenu()) ) )
 && ( (this.getRoleId()==castOther.getRoleId()) || ( this.getRoleId()!=null && castOther.getRoleId()!=null && this.getRoleId().equals(castOther.getRoleId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDataIdMenu() == null ? 0 : this.getDataIdMenu().hashCode() );
         result = 37 * result + ( getRoleId() == null ? 0 : this.getRoleId().hashCode() );
         return result;
   }   


}


